'use client';
import { useState } from 'react';
type Trace={tool:string;args:Record<string,unknown>;source:string;retrievedAt:string;ok:boolean};
export default function Analyst(){
  const [question,setQuestion]=useState('How did Aaron Judge perform in 2024 compared with 2023?');
  const [answer,setAnswer]=useState(''),[error,setError]=useState(''),[loading,setLoading]=useState(false),[trace,setTrace]=useState<Trace[]>([]);
  async function ask(e:React.FormEvent){e.preventDefault();setLoading(true);setAnswer('');setTrace([]);setError('');try{const response=await fetch('/api/agent',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({question})});const data=await response.json();setTrace(data.trace||[]);if(!response.ok)throw new Error(data.error);setAnswer(data.text);}catch(e){setError(e instanceof Error?e.message:'Request failed');}finally{setLoading(false);}}
  return <div><h1 style={{fontSize:36,fontWeight:700}}>AI Baseball Analyst</h1><p className="muted">Ask about players, standings, game previews or win predictions. The analyst can look up MLB data before writing an answer.</p><form onSubmit={ask} className="panel"><label htmlFor="question">Your baseball question</label><textarea id="question" value={question} onChange={e=>setQuestion(e.target.value)} maxLength={2000} required rows={4} style={{width:'100%',display:'block',padding:16,background:'var(--navy3)',margin:'12px 0',border:'1px solid var(--border)',borderRadius:8}}/><button className="action" disabled={loading}>{loading?'Retrieving data and analyzing…':'Ask analyst'}</button></form>{error&&<p role="alert">{error}</p>}{answer&&<section className="panel" style={{whiteSpace:'pre-wrap'}}>{answer}</section>}{trace.length>0&&<section className="panel"><h2>Data lookups</h2><p className="muted">These are the actual requests made for this answer.</p>{trace.map((t,i)=><div key={i} style={{padding:'12px 0',borderBottom:'1px solid var(--border)'}}><strong>{t.tool} · {t.ok?'Retrieved':'Unavailable'}</strong><pre style={{whiteSpace:'pre-wrap'}}>{JSON.stringify(t.args)}</pre><small>{t.source} · {new Date(t.retrievedAt).toLocaleString()}</small></div>)}</section>}</div>;
}
